cargo-features = ["edition"]

[package]
name = "tanya-render"
version = "0.1.0"
authors = ["msiglreith <m.siglreith@gmail.com>"]
edition = '2018'

[lib]
name = "tanya_render"
path = "src/lib.rs"

[dependencies]
d3d12 = { git = "https://github.com/msiglreith/d3d12-rs.git" }
