cargo-features = ["edition"]

[package]
name = "tanya"
version = "0.1.0"
authors = ["msiglreith <m.siglreith@gmail.com>"]
edition = '2018'

[workspace]
members = [
    "libjobs",
]

[dependencies]
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", rev = "cb03388" }
tanya-jobs = { path = "libjobs" }
rayon = { git = "https://github.com/msiglreith/rayon.git", branch = "futures" }

[[example]]
name = "jobs"
path = "examples/jobs.rs"
