[package]
name = "ash-vma"
version = "0.1.0"
authors = ["msiglreith <m.siglreith@gmail.com>"]
edition = '2018'
build = "build.rs"

[lib]
name = "ash_vma"
path = "src/lib.rs"

[dependencies]
ash = "0.26"

[build-dependencies]
cc = "1"
